// Objective-C API for talking to github.com/dcu/gomobile-sample Go package.
//   gobind -lang=objc -prefix=Go github.com/dcu/gomobile-sample
//
// File is generated by gobind. Do not edit.

#ifndef __GoSample_H__
#define __GoSample_H__

#include <Foundation/Foundation.h>
#include "GoUniverse.h"

FOUNDATION_EXPORT void GoSampleCrash();

FOUNDATION_EXPORT void GoSampleInit();

FOUNDATION_EXPORT long GoSampleSum(long a, long b);

#endif
