// Objective-C API for talking to github.com/dcu/gomobile-sample Go package.
//   gobind -lang=objc -prefix=Go github.com/dcu/gomobile-sample
//
// File is generated by gobind. Do not edit.

#ifndef __GoSample_H__
#define __GoSample_H__

#include <Foundation/Foundation.h>

FOUNDATION_EXPORT int GoSampleSum(int a, int b);

#endif
